version: '3'
services:
  server:
    image: docker-test/server
    build:
      context: ./
      dockerfile: server.dockerfile
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
  client:
    image: docker-test/client
    build:
      context: ./
      dockerfile: client.dockerfile
    command: npm run dev
    volumes:
      - ./client:/client
    ports:
      - "8080:8080"